### ISSUE TITLE
Bedrock endpoint hardcoded to us-east-1

### ISSUE THREAD

**Issue by developeper** [aws-samples/amazon-bedrock-kendra-lex-chatbot#6]
Hello,
when Fulfillment Intent invokes Lambda function I'm getting this error:
[ERROR] ValueError: Error raised by bedrock service: An error occurred (InvalidSignatureException) when calling the InvokeModel operation: Credential should be scoped to a valid region.
Checking Lambda's code I have found that Bedrock's endpoints URL are hardcoded to us-east-1 region:
llm_jurassic_ultra = Bedrock(
    model_id="ai21.j2-ultra-v1",
    endpoint_url="https://bedrock-runtime.us-east-1.amazonaws.com",
    model_kwargs={"temperature": 0.7, "maxTokens": 500, "numResults": 1}
)

llm_jurassic_mid = Bedrock(
    model_id="ai21.j2-mid-v1",
    endpoint_url="https://bedrock-runtime.us-east-1.amazonaws.com",
    model_kwargs={"temperature": 0.7, "maxTokens": 300, "numResults": 1}
)
While I've deployed the solution on us-west-2.
Since Bedrock is already available in different regions, it would make sense to setup the endpoint_url variable based on the region:
 endpoint_url="https://bedrock-runtime." +  region_name + ".amazonaws.com"

In addition, requirements.txt of the Lambda function has become a bit out of date.

**Comment by brettbs** [comment]
Thanks. Fixed
